# Generated by Django 2.2.6 on 2019-12-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20191220_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_invitation', to='notification.AccessToken'),
        ),
    ]
