# Generated by Django 2.2.6 on 2019-12-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20191220_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
