# Generated by Django 2.2.6 on 2020-01-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_collaborator_isconfirmed'),
        ('calendars', '0001_initial'),
        ('posts', '0002_auto_20191213_0904'),
        ('comment', '0001_initial'),
        ('notification', '0005_auto_20191220_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_post_notifications', to='calendars.Calendar')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_post_notifications', to='collaboration.Collaborator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='posts.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_post_comment_notifications', to='calendars.Calendar')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='comment.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_notifications', to='posts.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
