# Generated by Django 2.2.6 on 2020-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_commentnotification_postnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postnotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
