# Generated by Django 2.2.6 on 2019-12-08 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Editor', 'Editor'), ('Viewer', 'Viewer')], default='', max_length=20, null=True)),
                ('access', jsonfield.fields.JSONField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_calendar', to='calendars.Calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
