# Generated by Django 2.2.6 on 2019-12-11 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
from collaboration.consts import DefienedRoles

def create_default_roles(apps, schema_editor):
    Role = apps.get_model("collaboration", "Role")
    Role.objects.bulk_create([
        Role(name=DefienedRoles.OWNER, access=DefienedRoles.DEFAULT_ROLES[DefienedRoles.OWNER]),
        Role(name=DefienedRoles.MANAGER, access=DefienedRoles.DEFAULT_ROLES[DefienedRoles.MANAGER]),
        Role(name=DefienedRoles.EDITOR, access=DefienedRoles.DEFAULT_ROLES[DefienedRoles.EDITOR]),
        Role(name=DefienedRoles.VIEWER, access=DefienedRoles.DEFAULT_ROLES[DefienedRoles.VIEWER]),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('access', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_calendar', to='calendars.Calendar')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_role', to='collaboration.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_roles),
    ]
