# Generated by Django 2.2.6 on 2019-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
