# Generated by Django 2.2.6 on 2019-12-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='access',
        ),
    ]
