# Generated by Django 2.2.6 on 2019-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='postDefault.png', upload_to='D:\\Python-Workplace\\SE-Proj\\markit-backend\\markit-proj\\media'),
        ),
    ]
