# Generated by Django 2.2.6 on 2019-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishDateTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
