# Generated by Django 2.2.6 on 2019-12-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Publish Date and Time'),
        ),
    ]
