# Generated by Django 2.2.6 on 2019-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_publishdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishDateTime',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Publish Date and Time'),
        ),
    ]
