# Generated by Django 2.2.6 on 2019-12-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('posts', '0003_auto_20191128_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishTask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_publish_task', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Schdeuled', 'Scheduled')], default='Draft', max_length=9),
        ),
    ]
