# Generated by Django 2.2.6 on 2019-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191107_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='postDefault.png', upload_to='posts/'),
        ),
    ]
