# Generated by Django 2.2.6 on 2019-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191108_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/postDefault.png', upload_to='posts/'),
        ),
    ]
