# Generated by Django 2.2.6 on 2019-12-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191205_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishTask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_publish_task', to='django_celery_beat.PeriodicTask'),
        ),
    ]
