# Generated by Django 2.2.6 on 2019-12-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191206_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishTask',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='post_publish_task', to='django_celery_beat.PeriodicTask'),
        ),
    ]
