# Generated by Django 2.2.6 on 2019-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191206_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Schdeuled', 'Scheduled')], default='Draft', max_length=30),
        ),
    ]
