# Generated by Django 2.2.6 on 2019-12-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191206_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Scheduled', 'Scheduled')], default='Draft', max_length=30),
        ),
    ]
