# Generated by Django 2.2.6 on 2019-10-18 12:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=stdimage.models.StdImageField(blank=True, default='/static/profile.jpg', upload_to='profileImage', verbose_name='Profile Picture'),
        ),
    ]
