version: '3.7'

services:
  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: markit
      POSTGRES_DB: markitdb
      POSTGRES_PASSWORD: sebackendfall19
  redis:
    image: "redis:alpine"
  web:
    command: /bin/sh entrypoint.sh
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A markit worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  beat:
    build: .
    command: celery -A markit beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:




