# Generated by Django 2.2.6 on 2019-12-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Twitter', 'Twitter')], max_length=30, unique=True, verbose_name='provider')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('clientId', models.CharField(help_text='App ID, or consumer key', max_length=191, verbose_name='client id')),
                ('secret', models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191, verbose_name='secret key')),
            ],
            options={
                'verbose_name': 'social application',
                'verbose_name_plural': 'social applications',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Twitter', 'Twitter')], max_length=30, verbose_name='provider')),
                ('token', models.TextField(help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token')),
                ('tokenSecret', models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret')),
                ('expireDate', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialaccount_app', to='socials.SocialApp')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialaccount_calendar', to='calendars.Calendar')),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
            },
        ),
    ]
