# Generated by Django 2.2.6 on 2019-11-27 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], related_name='calendar_collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
