# Generated by Django 2.2.6 on 2019-12-07 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='calendar',
            name='editors',
            field=models.ManyToManyField(blank=True, default=[], related_name='calendar_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='managers',
            field=models.ManyToManyField(blank=True, default=[], related_name='calendar_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='viewers',
            field=models.ManyToManyField(blank=True, default=[], related_name='calendar_viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
