# Generated by Django 2.2.6 on 2019-11-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='user',
            new_name='users',
        ),
    ]
