# Generated by Django 2.2.6 on 2019-11-06 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20191106_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
