# Generated by Django 2.2.6 on 2019-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('calendars', '0002_auto_20191207_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='viewers',
        ),
        migrations.AddField(
            model_name='calendar',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], related_name='calendar_collaborators', to='collaboration.Collaborator'),
        ),
    ]
