# Generated by Django 2.2.6 on 2019-12-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20191208_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='collaborators',
        ),
    ]
