# Generated by Django 2.2.6 on 2019-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20191106_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='connected_platforms',
            field=models.CharField(blank=True, choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Facebook and Twitter', 'Facebook and Twitter')], default=None, max_length=20, null=True),
        ),
    ]
