# Generated by Django 2.2.6 on 2019-11-04 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('calendars', '0003_auto_20191104_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='socials',
            field=models.ManyToManyField(related_name='calendar_socials', to='socialaccount.SocialAccount'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(related_name='calendar_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
