# Generated by Django 2.2.6 on 2019-11-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20191106_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='connected_platforms',
            new_name='connectedPlatforms',
        ),
    ]
