# Generated by Django 2.2.6 on 2019-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_auto_20191106_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='connectedPlatforms',
            field=models.CharField(blank=True, choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Facebook and Twitter', 'Facebook and Twitter')], default='', max_length=20, null=True),
        ),
    ]
