# Generated by Django 2.2.6 on 2019-11-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('calendars', '0006_auto_20191106_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='twitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to='socialaccount.SocialAccount'),
        ),
    ]
