# Generated by Django 2.2.6 on 2019-11-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_calendar_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='twitter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to='socialaccount.SocialAccount'),
        ),
    ]
